### ISSUE TITLE
Add "primary" and "danger" button styles

### ISSUE THREAD

**Issue by therealklanni** [az-webdevs/azwebdevs.org#24]
Need to differentiate some of the types of buttons. Danger should be somewhere in the red part of the spectrum, and primary can be whatever you like and whatever you like for the default style.

**Comment by troym9731** [comment]
Since the default is already green, do you think we could get away with not having a primary and just the default color?

**Comment by therealklanni** [comment]
I think we're probably going to need a primary. Green should be for the "call to action" or "primary action" buttons, grey or other neutral for anything else. Danger could be optional, maybe. What do you think?

**Comment by troym9731** [comment]
Definitely a Danger option. Anything to signify a serious action like deletion. I can add primary, however, they should definitely be the theme-green, and therefore most buttons would be that color (which makes me want to make it default). Perhaps instead having Neutral and Danger instead? A little more uncommon, but I feel like the grey button may not get much use compared to primary.
